### ISSUE TITLE
nit: rename ecg_data

### ISSUE THREAD

**Issue by suyashkumar** [iruvdonuts/bme590hrm#34]
[Here](https://github.com/iruvdonuts/bme590hrm/blob/v1.0rc1/hrm.py#L10) you may want to consider renaming this variable to indicate that this is a data filename, perhaps to something like `input_data_file` or `ecg_data_file`. 

Generally with naming variables, it's a common heuristic in industry to try to have the code be as "self-documenting" as possible--if someone is skimming the code and sees a variable called `ecg_data` they may in this case think it's a structure containing the actual data as opposed to a filename until they read your docstring (which is okay, but again it's always nice to try and write self-documenting code)

(FYI "nit" means nitpick comment)

**Comment by suyashkumar** [comment]
Similarly [here](https://github.com/iruvdonuts/bme590hrm/blob/v1.0rc1/hrm.py#L20) you'd probably want to rename `data` to `ecg_data` to be more descriptive.

**Comment by suyashkumar** [comment]
Similarly [here](https://github.com/iruvdonuts/bme590hrm/blob/v1.0rc1/hrm.py#L25) it's unclear what `finalTimes` is--consider renaming to something like `peakTimes`

**Comment by suyashkumar** [comment]
Another small nit on naming [here](https://github.com/iruvdonuts/bme590hrm/blob/v1.0rc1/hrm.py#L51), _typically_ in python variables that are composed up of two words are in snake_case` so `minvoltage` should read as `min_voltage`.

**Comment by cshackerpro** [comment]
Are fixing these things in hrm.py also? Or just in hrm_class?

**Comment by suyashkumar** [comment]
(recap from what was mentioned on the PR): focus on getting the class based approach fixed first and then circle back to hrm.py to clean things up if you have time (it shouldn't take too long). :)

**Comment by cshackerpro** [comment]
We at least did this for
