### ISSUE TITLE
Questions for Palmeri and TAs

### ISSUE THREAD

**Issue by cshackerpro** [iruvdonuts/bme590hrm#7]
1. What will be the timescale for how long the ECG file will last
2. How long should the Brady and Tachy last in order for it to be reported?

**Comment by mlp6** [comment]
Stay tuned... announcement coming soon.

**Comment by suyashkumar** [comment]
Pretty sure we covered this when we chatted in class today, but just wanted to follow up here (let me know if I'm missing anything):
1. This is not strictly set in stone yet. There are data files out there that are up to 2 hours of ECG recording, so not sure if you should have anything dependent on the length of the ECG file. I would go ahead and say that 1 and 2 are independent in that if you have a really short ECG file (say 5 seconds), it's probably okay that you're not reporting any brady or tachy intervals in that time frame if your brady and tachy min time interval is longer than that (note that this should be configurable)

2. The threshold for the minimum intervals for brady- and tachy-cardia should be configurable, but go ahead and set something that you think is clinically meaningful as a default and that'll be okay (keep in mind how we plan on grading you and the grading rubric here is not focused on the clinical choice here). I think we'll send out some info on clinical stories regarding these conditions (feel free to look into it more yourself if you'd like--sepsis probably applies well to tachycardia and AV node problems perhaps apply to bradycardia, Dr. Palmeri can check me on that).
